/*
 * Area API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"encoding/json"
	"net/http"
	"strings"

	_ "github.com/gorilla/mux"
)

// A DefaultApiController binds http requests to an api service and writes the service results to the http response
type DefaultApiController struct {
	service DefaultApiServicer
}

// NewDefaultApiController creates a default api controller
func NewDefaultApiController(s DefaultApiServicer) Router {
	return &DefaultApiController{ service: s }
}

// Routes returns all of the api route for the DefaultApiController
func (c *DefaultApiController) Routes() Routes {
	return Routes{ 
		{
			"FindPointIntersections",
			strings.ToUpper("Post"),
			"/api/v1/intersections/point",
			c.FindPointIntersections,
		},
	}
}

// FindPointIntersections - Метод возвращает зоны, которые пересекаются с точкой, координаты которой передаются в запросе.
func (c *DefaultApiController) FindPointIntersections(w http.ResponseWriter, r *http.Request) { 
	pointIntersectionRequest := &PointIntersectionRequest{}
	if err := json.NewDecoder(r.Body).Decode(&pointIntersectionRequest); err != nil {
		w.WriteHeader(500)
		return
	}
	
	result, err := c.service.FindPointIntersections(r.Context(), *pointIntersectionRequest)
	//If an error occured, encode the error with the status code
	if err != nil {
		EncodeJSONResponse(err.Error(), &result.Code, w)
		return
	}
	//If no error, encode the body and the result code
	EncodeJSONResponse(result.Body, &result.Code, w)
	
}
