/*
 * Area API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// PointIntersectionRequest - Запрос пересечений с точкой.
type PointIntersectionRequest struct {

	// Широта.
	Latitude float64 `json:"latitude,omitempty"`

	// Долгота.
	Longitude float64 `json:"longitude,omitempty"`

	Levels []int32 `json:"levels,omitempty"`

	Interval Interval `json:"interval,omitempty"`
}
