/*
 * Area API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"time"
)

// Interval - Интервал
type Interval struct {

	// Начало
	From time.Time `json:"from,omitempty"`

	// Конец
	To time.Time `json:"to,omitempty"`
}
