/*
 * Area API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// WorkingDay : День недели.
type WorkingDay string

// List of WorkingDay
const (
	MONDAY WorkingDay = "MONDAY"
	TUESDAY WorkingDay = "TUESDAY"
	WEDNESDAY WorkingDay = "WEDNESDAY"
	THURSDAY WorkingDay = "THURSDAY"
	FRIDAY WorkingDay = "FRIDAY"
	SATURDAY WorkingDay = "SATURDAY"
	SUNDAY WorkingDay = "SUNDAY"
)
