/*
 * Area API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// AreaIntersection - Пересечение с зоной маршрутизатора.
type AreaIntersection struct {

	// Идентификатор зоны.
	Id int32 `json:"id,omitempty"`

	// Идентификатор родительской зоны.
	ParentId int32 `json:"parent_id,omitempty"`

	// Уровень зоны.
	Level int32 `json:"level,omitempty"`

	// Наименоание зоны.
	Name string `json:"name,omitempty"`

	// Идентификатор (номер) маршрута.
	RouteId int64 `json:"route_id,omitempty"`

	// Массив дней недели.
	WorkingDays []WorkingDay `json:"working_days,omitempty"`

	Intervals []Interval `json:"intervals,omitempty"`
}
